// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Video struct {
	ID           int32
	VideoID      string
	Title        string
	Description  sql.NullString
	PublishedAt  time.Time
	ChannelID    string
	ChannelTitle string
	Thumbnails   json.RawMessage
	FetchedAt    time.Time
}
