// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: videos.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const addVideo = `-- name: AddVideo :exec
INSERT INTO videos (
	video_id, title, description, published_at, channel_id, channel_title, thumbnails
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7
)
ON CONFLICT (video_id) DO NOTHING
`

type AddVideoParams struct {
	VideoID      string
	Title        string
	Description  sql.NullString
	PublishedAt  time.Time
	ChannelID    string
	ChannelTitle string
	Thumbnails   json.RawMessage
}

func (q *Queries) AddVideo(ctx context.Context, arg AddVideoParams) error {
	_, err := q.db.ExecContext(ctx, addVideo,
		arg.VideoID,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.ChannelID,
		arg.ChannelTitle,
		arg.Thumbnails,
	)
	return err
}
